name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.17
    - run: go get github.com/mitchellh/gox
    - uses: actions/checkout@v2
    - run: PATH=$HOME/go/bin:$PATH ./crossbuild.sh
    - uses: actions/upload-artifact@v1
      with:
        name: binaries
        path: binaries