name: Release

on:
  push:
    tags:
    - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - uses: actions/setup-go@v1
      with:
        go-version: 1.19
    - run: go install github.com/mitchellh/gox@latest
    - uses: actions/checkout@v2
    - run: PATH=$HOME/go/bin:$PATH ./crossbuild.sh
    - uses: svenstaro/upload-release-action@2.3.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: binaries/*
        tag: ${{ github.ref }}
        file_glob: "true"
        prerelease: "true"